[tests.did_change__add_new_text_package_header]
expected = """
Project KLS Test
I-- SourceSet kotlin
|   L-- File (src/main/kotlin/example.kt)
I       package example.com
I       =============
I       source_file
I         package_header (0, 0)-(0, 19) (package example.com)
I           package (0, 0)-(0, 7) (package)
I           identifier (0, 8)-(0, 19) (example.com)
I             simple_identifier (0, 8)-(0, 15) (example)
I             . (0, 15)-(0, 16) (.)
I             simple_identifier (0, 16)-(0, 19) (com)
I       =============
I       (0..19) package example.com
L-- SourceSet test (includes Api \"kotlin\" (SourceSet))"""
[tests.did_change__change_text_ast]
expected = """
Project KLS Test
I-- SourceSet kotlin
|   L-- File (src/main/kotlin/example.kt)
I       package mypackage.com
I       class B()
I       source_file
I         package_header (0, 0)-(0, 21) (package mypackage.com)
I           package (0, 0)-(0, 7) (package)
I           identifier (0, 8)-(0, 21) (mypackage.com)
I             simple_identifier (0, 8)-(0, 17) (mypackage)
I             . (0, 17)-(0, 18) (.)
I             simple_identifier (0, 18)-(0, 21) (com)
I         class_declaration (1, 0)-(1, 9) (class B())
I           class (1, 0)-(1, 5) (class)
I           type_identifier (1, 6)-(1, 7) (B)
I           primary_constructor (1, 7)-(1, 9) (())
I             ( (1, 7)-(1, 8) (()
I             ) (1, 8)-(1, 9) ())
L-- SourceSet test (includes Api \"kotlin\" (SourceSet))"""
[tests.did_change__delete_text_ast]
expected = """
Project KLS Test
I-- SourceSet kotlin
|   L-- File (src/main/kotlin/example.kt)
I       package com
I       class A()
I       source_file
I         package_header (0, 0)-(0, 11) (package com)
I           package (0, 0)-(0, 7) (package)
I           identifier (0, 8)-(0, 11) (com)
I             simple_identifier (0, 8)-(0, 11) (com)
I         class_declaration (1, 0)-(1, 9) (class A())
I           class (1, 0)-(1, 5) (class)
I           type_identifier (1, 6)-(1, 7) (A)
I           primary_constructor (1, 7)-(1, 9) (())
I             ( (1, 7)-(1, 8) (()
I             ) (1, 8)-(1, 9) ())
L-- SourceSet test (includes Api \"kotlin\" (SourceSet))"""

[tests.did_change__replace_existing_package_header]
expected = """
Project KLS Test
I-- SourceSet kotlin
|   L-- File (src/main/kotlin/example.kt)
I       package update2.package.com
I                           =============
I       source_file
I         package_header (0, 0)-(0, 27) (package update2.package.com)
I           package (0, 0)-(0, 7) (package)
I           identifier (0, 8)-(0, 27) (update2.package.com)
I             simple_identifier (0, 8)-(0, 15) (update2)
I             . (0, 15)-(0, 16) (.)
I             simple_identifier (0, 16)-(0, 23) (package)
I             . (0, 23)-(0, 24) (.)
I             simple_identifier (0, 24)-(0, 27) (com)
I       =============
I       (0..27) package update2.package.com
L-- SourceSet test (includes Api \"kotlin\" (SourceSet))"""
