[tests.project_source_set_nodes]
expected = """
Project KLS Test
I-- SourceSet kotlin
|   L-- File (src/main/kotlin/example.kt)
I       package example.com
L-- SourceSet test (includes Api \"kotlin\" (SourceSet))"""
